### ISSUE TITLE
ModuleNotFoundError: No module named 'obspy'

### ISSUE THREAD

**Issue by thbeutin** [SCECcode/csep2#7]
I try to test my code, but run into an nasty error not resolvable by my OS pkg mgr:

```
/usr/bin/python3.6 /snap/pycharm-community/179/plugins/python-ce/helpers/pydev/pydevconsole.py --mode=client --port=39395

import sys; print('Python %s on %s' % (sys.version, sys.platform))
sys.path.extend(['/home/tb/PycharmProjects/csep2'])

Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
Type "copyright", "credits" or "license" for more information.

IPython 5.5.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
PyDev console: using IPython 5.5.0

Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
In[2]: from csep.core.catalogs import JmaCsvCatalog
Backend TkAgg is interactive backend. Turning interactive mode on.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-8f4b98ac0bf6>", line 1, in <module>
    from csep.core.catalogs import JmaCsvCatalog
  File "/snap/pycharm-community/179/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/tb/PycharmProjects/csep2/csep/__init__.py", line 2, in <module>
    from csep.core.catalogs import UCERF3Catalog, CSEPCatalog, ComcatCatalog
  File "/snap/pycharm-community/179/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/tb/PycharmProjects/csep2/csep/core/catalogs.py", line 13, in <module>
    from csep.utils.comcat import search
  File "/snap/pycharm-community/179/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/tb/PycharmProjects/csep2/csep/utils/comcat.py", line 26, in <module>
    from obspy.core.event import read_events
  File "/snap/pycharm-community/179/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'obspy'
```

If obspy is a hard dependency shouldn't a specific version be a submodule of this project?

**Comment by thbeutin** [comment]
i've found a Debian/Ubuntu/Mint repo for _obspy_:

```
$ cat /etc/apt/sources.list.d/obspy.list 
deb http://deb.obspy.org bionic main
tb@tokaido:~/PycharmProjects/csep2$ 
```

So i consider this solved.
