### ISSUE TITLE
one unit test failes

### ISSUE THREAD

**Issue by thbeutin** [SCECcode/csep2#8]
```
tb@tokaido:~/PycharmProjects/csep2$ python3 -m unittest
..../usr/lib/python3.6/tempfile.py:939: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmpfnbtlb0q'>
  _warnings.warn(warn_message, ResourceWarning)
....[ 2.  2.  2.  0.  0.  0.  0.  0.  0.  0.  2.  0.]
.......E..........................
======================================================================
ERROR: test_catalog_create_with_failure (tests.test_create_catalog.TestCreateCatalog)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tb/PycharmProjects/csep2/tests/test_create_catalog.py", line 16, in test_catalog_create_with_failure
    AbstractBaseCatalog(catalog=catalog)
  File "/home/tb/PycharmProjects/csep2/csep/core/catalogs.py", line 49, in __init__
    self.catalog = catalog
  File "/home/tb/PycharmProjects/csep2/csep/core/catalogs.py", line 190, in catalog
    self._catalog = self._get_catalog_as_ndarray()
  File "/home/tb/PycharmProjects/csep2/csep/core/catalogs.py", line 501, in _get_catalog_as_ndarray
    catalog = numpy.array(n, dtype=self.dtype)
TypeError: a bytes-like object is required, not 'int'

----------------------------------------------------------------------
Ran 42 tests in 0.013s

FAILED (errors=1)
tb@tokaido:~/PycharmProjects/csep2$ 
```

**Comment by thbeutin** [comment]
i've to use `pytest-3` (instead of `pytest`), but it gives the same error:

```
tb@tokaido:~/PycharmProjects/csep2$ pytest-3 
============================================================================================================ test session starts =============================================================================================================
platform linux -- Python 3.6.9, pytest-3.3.2, py-1.5.2, pluggy-0.6.0
rootdir: /home/tb/PycharmProjects/csep2, inifile:
plugins: pylint-0.8.0
collected 73 items                                                                                                                                                                                                                           

tests/test_UCERF3Forecast.py ....                                                                                                                                                                                                      [  5%]
tests/test_acceptance_ucerf3_experiment.py .                                                                                                                                                                                           [  6%]
tests/test_adaptiveHistogram.py ......                                                                                                                                                                                                 [ 15%]
tests/test_basic_types_utils.py .                                                                                                                                                                                                      [ 16%]
tests/test_calc.py ...                                                                                                                                                                                                                 [ 20%]
tests/test_comcat.py ......                                                                                                                                                                                                            [ 28%]
tests/test_create_catalog.py F.                                                                                                                                                                                                        [ 31%]
tests/test_evaluations.py ....                                                                                                                                                                                                         [ 36%]
tests/test_file_system.py ..                                                                                                                                                                                                           [ 39%]
tests/test_generate_runtime_enviornment.py ..                                                                                                                                                                                          [ 42%]
tests/test_math.py ..............                                                                                                                                                                                                      [ 61%]
tests/test_stats.py ................                                                                                                                                                                                                   [ 83%]
tests/test_system.py ....                                                                                                                                                                                                              [ 89%]
tests/test_time_utilities.py ......                                                                                                                                                                                                    [ 97%]
tests/test_workflow.py ..                                                                                                                                                                                                              [100%]

================================================================================================================== FAILURES ==================================================================================================================
_____________________________________________________________________________________________ TestCreateCatalog.test_catalog_create_with_failure _____________________________________________________________________________________________

self = <tests.test_create_catalog.TestCreateCatalog testMethod=test_catalog_create_with_failure>

    def test_catalog_create_with_failure(self):
        catalog = 'failure condition!'
        with self.assertRaises(ValueError):
>           AbstractBaseCatalog(catalog=catalog)

tests/test_create_catalog.py:16: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
csep/core/catalogs.py:49: in __init__
    self.catalog = catalog
csep/core/catalogs.py:190: in catalog
    self._catalog = self._get_catalog_as_ndarray()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    def _get_catalog_as_ndarray(self):
        """
            This function must be implemented if the catalog is loaded in a bespoke format.
            This function will be called anytime that a catalog is assigned
            to self.catalog and is not of type ndarray.
    
            The structure of the ndarray does not matter, so long as the getters can be
            implemented correctly.
    
            Additionally, advanced catalog operations could be carried out using GeoDataFrames and
            DataFrames.
            """
        if isinstance(self.catalog, numpy.ndarray):
            return self.catalog
        n = len(self.catalog)
>       catalog = numpy.array(n, dtype=self.dtype)
E       TypeError: a bytes-like object is required, not 'int'

csep/core/catalogs.py:501: TypeError
==================================================================================================== 1 failed, 72 passed in 3.44 seconds =====================================================================================================
tb@tokaido:~/PycharmProjects/csep2$
```

**Comment by wsavran** [comment]
this is likely related to your environment not being consistent with the development environment. closing this issue and try again when #9 is resolved.

**Comment by thbeutin** [comment]
After After setting up the `venv` in a proper way, the command `python3 -m unittest` didn't work at all anymore (`FAILED (errors=15)`), but instead 'pytest-3' (but not just 'pytest' from `./run_tests.sh`!) finished w/o errors.

**Comment by wsavran** [comment]
thx for update. ill repoen this until i solve the pytest-3 issue.
